name: frontend_flutter
description: The new way to communicate with your friends and family by merging the efficiency of voice calls with the convenience of messaging. 
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  rxdart: ^0.20.0
  http: ^0.12.0+1
  eventsource: ^0.2.1
  flutter_webrtc: ^0.1.0
  pin_code_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.svg
    - assets/logo.png

  fonts:
  - family: Inter
    fonts:
      # TODO: avoid bundling unused fonts check in future versions
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-Semibold.ttf
        weight: 600
