name: frontend_flutter
description: The new way to communicate with your friends and family by merging the efficiency of voice calls with the convenience of messaging.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  rxdart: ^0.20.0
  http: ^0.12.0+1
  pin_code_text_field: ^1.1.3
  flutter_svg: ^0.13.1
  shared_preferences: ^0.5.1
  sqflite: ^1.1.0
  eventsource: ^0.2.1
  sticky_headers: ^0.1.7
  image_picker_modern: ^0.4.12+2
  flutter_spinkit: ^3.1.0
  unique_identifier: ^0.0.3
  contacts_service: ^0.2.8
  path_provider: ^1.1.0
  flutter_slidable: ^0.5.3
  image_jpeg: ^1.1.1
  permission_handler: ^4.0.0
  connectivity: ^0.4.6+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/phoneno.svg
    - assets/welcome.svg
    - assets/authenticate.svg

  fonts:
  - family: Inter
    fonts:
      # TODO: avoid bundling unused fonts check in future versions
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-Semibold.ttf
        weight: 600
